### ISSUE TITLE
credentials.js가 공개되어 있는데 괜찮은 건가요?

### ISSUE THREAD

**Issue by rycont** [junhoyeo/dimi-online-notification-frontend#2]

**Comment by junhoyeo** [comment]
https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public
위 내용처럼 파이어베이스 프로젝트의 식별자로만 사용되고, 클라우드 메세징을 위해서만 사용되므로 딱히 문제가 없을 것 같아요!
